language: cpp

jobs:
  include:
    - os: osx
      compiler: gcc
      osx_image: xcode11.2
      addons:
        apt:
          packages:
            - ccache
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      addons:
        apt:
          packages:
            - ccache
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          packages:
            - ccache
    - os: linux
      dist: focal
      compiler: clang
      addons:
        apt:
          packages:
            - ccache

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j
