language: cpp

jobs:
  include:
    - os: osx
      compiler: gcc
      osx_image: xcode11.2    # includes gcc-9 by default
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      env:
        - MATRIX_EVAL=""
    - os: linux
      dist: focal
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
      env:
        - GCC_VER="9"
        - MATRIX_EVAL="CC=gcc-${GCC_VER} && CXX=g++-${GCC_VER}"
    - os: linux
      dist: focal
      compiler: clang
      env:
        - MATRIX_EVAL=""


before_script:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j
  # - cmake -D ENABLE_COVERAGE:BOOL=TRUE ../
  # - cmake --build . -- -j2
  # - ctest -j2
